<?php

namespace EPSI\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * newsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class newsRepository extends EntityRepository
{
    public function getNews()
    {
        $query = $this->createQueryBuilder('n')
                ->orderBy('n.date', 'DESC')
                ->getQuery();
        return $query->getResult();
    }
    
    public function getNewsById($id)
    {
        $new = parent::find($id);
        return $new;
    }
}
